### ISSUE TITLE
Add a setup.py (and upload to pypi?) so heinrichy can be installed.

### ISSUE THREAD

**Issue by waynew** [MichPCX/Richy#6]
You can use a setup.py file and stick an [`entry point`](https://github.com/waynew/termdown/blob/master/setup.py#L40-L44) in there so that the heinrichy command is created. This will actually allow it be installed on both Linux *and* Windows, and will just do The Right Thing :)

**Comment by MichPCX** [comment]
It will take a while but I am working on this feature to Heinrichy where you can simply just type `heinrichy what day is today?` and it will give you the answer for your question instead of running everything.

**Comment by MichPCX** [comment]
@waynew Closing this as Heinrichy (now Richy) can be installed using `setup.py` file. Thanks for the idea!
